import { supabase } from './supabaseClient.js';

const clone = v => structuredClone(v);
const requireClient = () => { if (!supabase) throw new Error('Supabase is not configured. Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to .env.local.'); return supabase; };
const isoMs = x => x ? new Date(x).getTime() : null;
const fromQuestion = (q, v, tags=[]) => ({
  id:q.id, question_code:q.question_code, versionId:v?.id, question:v?.question_text||'', category:v?.category||'General', tags, explanation:v?.explanation||'', answers:v?.answers||[], correctIndex:v?.correct_index??0, status:q.status, ownerId:q.owner_id, created_at:q.created_at, updated_at:q.updated_at,
  history:[]
});
const fromQuiz = (q, v, qs=[]) => {
  const s=v?.settings||{};
  return { id:q.id, quiz_code:q.quiz_code, title:q.title, category:v?.category||'General', tags:s.tags||[], description:v?.description||'', mode:v?.mode||'practice', status:q.status, questionIds:qs.map(x=>x.question_version_id), questionCount:qs.length, timeLimit:s.time_limit_seconds ? Math.round(s.time_limit_seconds/60) : null, access:v?.access_level||'registered', review:s.review||'full', randomizeQuestions:!!s.randomize_questions, randomizeAnswers:!!s.randomize_answers, flagging:s.flagging!==false, selectionRules:s.selection_rules||null, navigation:s.navigation==='sequential'?'sequential':'free', availableFrom:s.available_from||null, availableTo:s.available_to||null, ownerId:q.owner_id, versionId:v?.id, publishedAt:v?.published_at, created_at:q.created_at, updated_at:q.updated_at };
};

async function latestQuestionVersions(ids) {
  const c=requireClient(); if(!ids?.length) return [];
  const {data,error}=await c.from('question_versions').select('*').in('id',ids); if(error) throw error;
  const qids=[...new Set(data.map(v=>v.question_id))]; const {data:qs,error:qe}=await c.from('questions').select('*').in('id',qids); if(qe) throw qe;
  const {data:qt}=await c.from('question_tags').select('question_version_id,tags(name)').in('question_version_id',ids);
  const tagsBy=new Map(); (qt||[]).forEach(r=>(tagsBy.get(r.question_version_id)||tagsBy.set(r.question_version_id,[]).get(r.question_version_id)).push(r.tags?.name).filter(Boolean));
  const byId=new Map(qs.map(q=>[q.id,q])); return data.map(v=>fromQuestion(byId.get(v.question_id),v,tagsBy.get(v.id)||[]));
}

export const repository = {
 async getSession(){ const c=requireClient(); const {data}=await c.auth.getSession(); return {identity:data.session?.user?.id||'guest'}; },
 async getCurrentUser(){ const c=requireClient(); const {data:{user}}=await c.auth.getUser(); if(!user) return null; const {data:p,error}=await c.from('profiles').select('*').eq('id',user.id).single(); if(error) throw error; return {id:user.id,name:p.display_name||user.email?.split('@')[0]||'User',email:user.email,role:p.role}; },
 async setSession(action){ const c=requireClient(); if(action==='guest'){await c.auth.signOut();return {identity:'guest'};} return this.getSession(); },
 async listQuizzes(filter={}){ const c=requireClient(); let query=c.from('quizzes').select('*,quiz_versions(*),quiz_questions(*)').order('created_at',{ascending:false}); if(filter.ownerId) query=query.eq('owner_id',filter.ownerId); const {data,error}=await query; if(error) throw error; return (data||[]).map(q=>{const vs=(q.quiz_versions||[]).sort((a,b)=>b.version_number-a.version_number);const v=vs[0];const qs=(q.quiz_questions||[]).filter(x=>x.quiz_version_id===v?.id).sort((a,b)=>a.selection_order-b.selection_order);return fromQuiz(q,v,qs);}); },
 async getQuiz(id){ const xs=await this.listQuizzes(); return clone(xs.find(q=>q.id===id)); },
 async getQuestions(ids){ return latestQuestionVersions(ids); },
 async listQuestions(filter={}){ const c=requireClient(); let q=c.from('questions').select('*').order('created_at',{ascending:false}); if(filter.ownerId) q=q.eq('owner_id',filter.ownerId); const {data,error}=await q; if(error) throw error; const out=[]; for(const row of data||[]){const {data:vs,error:e}=await c.from('question_versions').select('*').eq('question_id',row.id).order('version_number',{ascending:false}).limit(1);if(e)throw e; if(vs?.[0]) out.push(fromQuestion(row,vs[0],[]));} return out; },
 async createQuestion(data){ const c=requireClient(); const user=await this.getCurrentUser(); const code=`${String(data.category||'GEN').replace(/[^A-Za-z]/g,'').slice(0,3).toUpperCase()||'GEN'}-${String(data.tags?.[0]||'GEN').replace(/[^A-Za-z0-9]/g,'').toUpperCase()}-${Math.floor(100000+Math.random()*900000)}`; const {data:q,error}=await c.from('questions').insert({question_code:code,owner_id:user?.id||null,status:'draft'}).select().single();if(error)throw error;const {data:v,error:ve}=await c.from('question_versions').insert({question_id:q.id,version_number:1,question_text:data.question,category:data.category||'General',explanation:data.explanation||'',answers:data.answers||[],correct_index:data.correctIndex||0}).select().single();if(ve)throw ve;return fromQuestion(q,v,data.tags||[]); },
 async updateQuestion(id,patch){ const c=requireClient(); const {data:q,error:qe}=await c.from('questions').select('*').eq('id',id).single();if(qe)throw qe;const {data:vs,error:ve}=await c.from('question_versions').select('*').eq('question_id',id).order('version_number',{ascending:false}).limit(1);if(ve)throw ve;const v=vs[0];const content=['question','category','explanation','answers','correctIndex','tags'].some(k=>k in patch);if(content){const next={question_text:patch.question??v.question_text,category:patch.category??v.category,explanation:patch.explanation??v.explanation,answers:patch.answers??v.answers,correct_index:patch.correctIndex??v.correct_index,question_id:id,version_number:v.version_number+1};const {data:nv,error}=await c.from('question_versions').insert(next).select().single();if(error)throw error;return fromQuestion(q,nv,patch.tags||[]);}return fromQuestion(q,v,[]); },
 async getQuestionHistory(id){ const c=requireClient();const {data,error}=await c.from('question_versions').select('*').eq('question_id',id).order('version_number');if(error)throw error;return (data||[]).map(v=>({versionId:v.id,question:v.question_text,category:v.category,explanation:v.explanation,answers:v.answers,correctIndex:v.correct_index,savedAt:v.created_at,note:'Version'})); },
 async revertQuestion(id,versionId){ const c=requireClient();const {data:v,error}=await c.from('question_versions').select('*').eq('id',versionId).single();if(error)throw error;return this.updateQuestion(id,{question:v.question_text,category:v.category,explanation:v.explanation,answers:v.answers,correctIndex:v.correct_index}); },
 async listAttempts(){ const c=requireClient();const u=await this.getCurrentUser();if(!u)return [];const {data,error}=await c.from('attempts').select('*,quiz_versions(quiz_id,mode,quizzes(title))').eq('user_id',u.id).order('created_at',{ascending:false});if(error)throw error;return (data||[]).map(a=>({id:a.id,quizId:a.quiz_versions?.quiz_id,quizTitle:a.quiz_versions?.quizzes?.title||'Quiz',mode:a.quiz_versions?.mode,status:a.status,date:a.created_at,correctCount:a.correct_count||0,totalCount:a.total_count,expiresAt:isoMs(a.expires_at),userId:a.user_id,randomization:{questionOrder:a.question_order||[],answerMapping:a.answer_mapping||{}},responses:a.responses||{}})); },
 async getAttempt(id){const xs=await this.listAttempts();return xs.find(a=>a.id===id);},
 async getActiveAttempt(quizId){const xs=await this.listAttempts();return xs.find(a=>a.quizId===quizId&&a.status==='in_progress');},
 async saveAttempt(a){ return a; },
 async startAttempt(quizId){const c=requireClient();const q=await this.getQuiz(quizId);if(!q)throw new Error('Quiz not found');const {data,error}=await c.rpc('start_attempt',{p_quiz_version_id:q.versionId,p_assignment_id:null});if(error)throw error;return data;},
 async getAttemptQuestions(attemptId){const c=requireClient();const {data,error}=await c.rpc('get_attempt_questions',{p_attempt_id:attemptId});if(error)throw error;return data||[];},
 async finalizeAttempt(id,responses){const c=requireClient();const {data,error}=await c.rpc('finalize_attempt',{p_attempt_id:id,p_responses:responses});if(error)throw error;return data;},
 async createQuiz(data){const c=requireClient();const u=await this.getCurrentUser();if(!u || !['admin','teacher'].includes(u.role)) throw new Error('Teacher or admin access required');const ownerId=data.ownerId||u.id;const {data:q,error:qe}=await c.from('quizzes').insert({quiz_code:data.quiz_code,title:data.title,owner_id:ownerId,status:data.status||'draft'}).select().single();if(qe)throw qe;const settings={tags:data.tags||[],review:data.review||'full',randomize_questions:!!data.randomizeQuestions,randomize_answers:!!data.randomizeAnswers,flagging:data.flagging!==false,navigation:data.navigation==='sequential'?'sequential':'free',selection_rules:data.selectionRules||null,time_limit_seconds:data.timeLimit?Number(data.timeLimit)*60:null,available_from:data.availableFrom||null,available_to:data.availableTo||null};const {data:v,error:ve}=await c.from('quiz_versions').insert({quiz_id:q.id,version_number:1,mode:data.mode||'practice',access_level:data.access||'registered',category:data.category||'General',description:data.description||'',settings,published_at:data.status==='published'?(data.publishedAt||new Date().toISOString()):null}).select().single();if(ve)throw ve;if(data.questionIds?.length){const rows=data.questionIds.map((id,i)=>({quiz_version_id:v.id,question_version_id:id,selection_order:i+1}));const {error:qe2}=await c.from('quiz_questions').insert(rows);if(qe2)throw qe2;}return fromQuiz(q,v,(data.questionIds||[]).map((question_version_id,i)=>({question_version_id,selection_order:i+1})));},
 async updateQuiz(id,patch){const c=requireClient();const u=await this.getCurrentUser();if(!u || !['admin','teacher'].includes(u.role)) throw new Error('Teacher or admin access required');const {data:q,error:qe}=await c.from('quizzes').select('*').eq('id',id).single();if(qe)throw qe;if(u.role!=='admin' && q.owner_id!==u.id) throw new Error('You do not own this quiz');const {data:vs,error:ve}=await c.from('quiz_versions').select('*').eq('quiz_id',id).order('version_number',{ascending:false}).limit(1);if(ve)throw ve;const old=vs[0];const nextStatus=patch.status||q.status;const settings={...(old?.settings||{}),tags:patch.tags??old?.settings?.tags??[],review:patch.review??old?.settings?.review??'full',randomize_questions:patch.randomizeQuestions??old?.settings?.randomize_questions??false,randomize_answers:patch.randomizeAnswers??old?.settings?.randomize_answers??false,flagging:patch.flagging??old?.settings?.flagging??true,navigation:patch.navigation??old?.settings?.navigation??'free',selection_rules:patch.selectionRules??old?.settings?.selection_rules??null,time_limit_seconds:patch.timeLimit!=null?(Number(patch.timeLimit)*60):old?.settings?.time_limit_seconds??null,available_from:patch.availableFrom??old?.settings?.available_from??null,available_to:patch.availableTo??old?.settings?.available_to??null};const {error:qu}=await c.from('quizzes').update({title:patch.title??q.title,quiz_code:patch.quiz_code??q.quiz_code,status:nextStatus}).eq('id',id);if(qu)throw qu;const {data:v,error:ie}=await c.from('quiz_versions').insert({quiz_id:id,version_number:(old?.version_number||0)+1,mode:patch.mode??old?.mode??'practice',access_level:patch.access??old?.access_level??'registered',category:patch.category??old?.category??'General',description:patch.description??old?.description??'',settings,published_at:nextStatus==='published'?(patch.publishedAt||old?.published_at||new Date().toISOString()):null}).select().single();if(ie)throw ie;if(patch.questionIds){const rows=patch.questionIds.map((question_version_id,i)=>({quiz_version_id:v.id,question_version_id,selection_order:i+1}));if(rows.length){const {error:qe2}=await c.from('quiz_questions').insert(rows);if(qe2)throw qe2;}}return fromQuiz({...q,...(patch.title?{title:patch.title}:{}),status:nextStatus},v,(patch.questionIds||[]).map((question_version_id,selection_order)=>({question_version_id,selection_order:selection_order+1})));},
 async getPlatformSettings(){const c=requireClient();const {data,error}=await c.from('platform_settings').select('*').single();if(error)throw error;return {teacherModeEnabled:data.teacher_mode_enabled};},
 async setTeacherMode(enabled){const c=requireClient();const {data,error}=await c.from('platform_settings').update({teacher_mode_enabled:!!enabled}).eq('id',true).select().single();if(error)throw error;return {teacherModeEnabled:data.teacher_mode_enabled};},
 async getGuestState(){return JSON.parse(localStorage.getItem('quizlab.guest')||'{"allocationUsed":false}');},
 async useGuestAllocation(){const s={allocationUsed:true};localStorage.setItem('quizlab.guest',JSON.stringify(s));return s;},
 async users(){return [];},
 async listGroups(){const c=requireClient();const u=await this.getCurrentUser();if(!u)return [];const {data,error}=await c.from('groups').select('*').eq('owner_id',u.id);if(error)throw error;return (data||[]).map(g=>({id:g.id,name:g.name,code:null,teacherId:g.owner_id,memberIds:[]}));},
 async getGroup(id){const c=requireClient();const {data,error}=await c.from('groups').select('*').eq('id',id).single();if(error)throw error;return {id:data.id,name:data.name,code:null,teacherId:data.owner_id,memberIds:[]};},
 async createGroup({name}){const c=requireClient();const u=await this.getCurrentUser();const {data,error}=await c.from('groups').insert({name,owner_id:u.id}).select().single();if(error)throw error;return {id:data.id,name:data.name,teacherId:data.owner_id,memberIds:[]};},
 async deleteGroup(id){const c=requireClient();const {error}=await c.from('groups').delete().eq('id',id);if(error)throw error;},
 async joinGroupByCode(){throw new Error('Group join codes are being moved to the secure server function.');},
 async removeGroupMember(){throw new Error('Use the teacher group controls.');},
 async addGroupMembers(){throw new Error('Roster import is being moved to the secure server function.');},
 async listGroupsForMember(){return [];},
 async listAssignments(){const c=requireClient();const {data,error}=await c.from('assignments').select('*');if(error)throw error;return (data||[]).map(a=>({id:a.id,groupId:a.group_id,quizId:null,dueAt:a.ends_at,assignedBy:a.created_by}));},
 async createAssignment(data){const c=requireClient();const {error}=await c.from('assignments').insert(data);if(error)throw error;return data;},
 async createAssignments(data){return Promise.all((data||[]).map(x=>this.createAssignment(x)));},
 async deleteAssignment(id){const c=requireClient();const {error}=await c.from('assignments').delete().eq('id',id);if(error)throw error;},
 async isUserAssignedQuiz(userId,quizId){const c=requireClient();const q=await this.getQuiz(quizId);if(!q)return false;const {data,error}=await c.from('assignments').select('id').eq('quiz_version_id',q.versionId).or(`learner_id.eq.${userId}`);if(error)throw error;return !!data?.length;},
 async listAttemptsForUser(userId){return (await this.listAttempts()).filter(a=>a.userId===userId);}
};
